export const Information: {
  name: string
  catalog: { name: string; url: string }[]
}[] = [
  {
    name: "Каталог",
    catalog: [
      { name: "Вудилища", url: "fishingrod" },
      { name: "Котушки", url: "coils" },
      { name: "Жилки", url: "veins" },
      { name: "Шнури", url: "cords" },
      { name: "Готове оснащення", url: "readyequipment" },
      { name: "Поплавці та маркери", url: "floats&markers" },
      { name: "Все для монтажу", url: "everythingforinstallation" },
      { name: "Інструменти для бойлів і пелетсу", url: "boiles&pellets" },
      { name: "Гачки", url: "hooks" },
      { name: "Приманки", url: "lures" },
      { name: "Прикормки", url: "baits" },
      { name: "Підгодовування", url: "feeding" },
      { name: "Відра", url: "buskets" },
      { name: "Сита", url: "satisfied" },
      { name: "Підставки й тримачі", url: "stand&holders" },
      { name: "Електронні сигналізатори", url: "electronicsignaldevices" },
      { name: "Механічні сигналізатори", url: "mechanicalsignaldevices" },
      { name: "Підсаки й багри", url: "podsaks&bagras" },
      { name: "Садки, кукани й кани", url: "gardenshuts&cans" },
      { name: "Догляд за коропом", url: "carpcare" },
      { name: "Транспортування й зберігання", url: "transportation&storage" },
      { name: "Парасолі", url: "umbrellas" },
      {
        name: "Платформи, крісла та навісне обладнання",
        url: "platforms&chairs",
      },
      { name: "Зимова ловля", url: "winterfishing" },
      { name: "Одяг", url: "clothes" },
      { name: "Рушники", url: "towels" },
      { name: "Інструменти", url: "tools" },
      { name: "Cyberfishing", url: "cyberfishing" },
      { name: "Туризм", url: "tourism" },
      { name: "Човни й мотори", url: "boats&motors" },
      {
        name: "Ехолоти, навігатори і аксесуари",
        url: "echosounders&navigatiros",
      },
      { name: "Сувенірна продукція", url: "souvenirproducts" },
      { name: "Акційні набори", url: "promotionssets" },
      { name: "Подарункові сертифікати Flagman", url: "giftcertificates" },
      { name: "Запчастини й догляд", url: "spareparts&maintenance" },
      { name: "Тактичне спорядження", url: "tcticalequipment" },
      { name: "Автономне живлення", url: "autonomouspowersupply" },
    ],
  },
  {
    name: "Спінінг",
    catalog: [
      { name: "Вудилища", url: "fishingrod" },
      { name: "Котушки", url: "coils" },
      { name: "Шнури", url: "cords" },
      { name: "Жилки", url: "veins" },
      { name: "Гачки", url: "hooks" },
      { name: "Силіконові принади", url: "siliconecharms" },
      { name: "Блешні", url: "bleshni" },
      { name: "Гачки", url: "wobblers" },
      { name: "Спіннербейти", url: "spinnerbaits" },
      { name: "Паста форель", url: "troutpasta" },
      { name: "Підгодовування", url: "" },
      { name: "Атрактанти", url: "attractants" },
      { name: "Все для монтажу", url: "everythingforinstallation" },
      { name: "Джиг-головки", url: "jigheads" },
      { name: "Грузила", url: "sinking" },
      { name: "Застібки", url: "fasteners" },
      { name: "Вертлюги", url: "spinners" },
      { name: "Поплавці", url: "floats" },
      { name: "Готові оснащення", url: "readyequipment" },
      { name: "Підсаки", url: "podsacks" },
      { name: "Голови підсак", url: "headsofpodsak" },
      { name: "Ручки підсак", url: "pockethandles" },
      { name: "Багри", url: "brownhair" },
      { name: "Cадки і кукани", url: "gardens&cottages" },
      { name: "Кукани", url: "kukans" },
      { name: "Кани", url: "kany" },
      { name: "Інструменти", url: "tools" },
      { name: "Мультитули", url: "multitools" },
      { name: "Набори інструментів", url: "toolsets" },
      { name: "Зівники", url: "zivniki" },
      { name: "Екіпірування", url: "equipment" },
      { name: "Рукавички спінінгіста", url: "spinninggloves" },
      { name: "Розвантажувальні жилети", url: "lifejackets" },
      { name: "Забродні чоботи", url: "dirtyboots" },
      { name: "Забродні костюми", url: "outlandishcostumes" },
      { name: "Коробки", url: "boxes" },
    ],
  },
  {
    name: "Фідер",
    catalog: [
      { name: "Вудилища", url: "" },
      { name: "Котушки", url: "" },
      { name: "Шнури", url: "" },
      { name: "Жилки", url: "" },
      { name: "Гачки", url: "" },
      { name: "Силіконові принади", url: "" },
      { name: "Блешні", url: "" },
      { name: "Воблери", url: "" },
      { name: "Гачки", url: "" },
      { name: "Приманки", url: "" },
      { name: "Прикормки", url: "" },
      { name: "Підгодовування", url: "" },
      { name: "Відра", url: "" },
      { name: "Сита", url: "" },
      { name: "Підставки й тримачі", url: "" },
      { name: "Електронні сигналізатори", url: "" },
      { name: "Механічні сигналізатори", url: "" },
      { name: "Підсаки й багри", url: "" },
      { name: "Садки, кукани й кани", url: "" },
      { name: "Догляд за коропом", url: "" },
      { name: "Транспортування й зберігання", url: "" },
      { name: "Парасолі", url: "" },
      { name: "Платформи, крісла та навісне обладнання", url: "" },
      { name: "Зимова ловля", url: "" },
      { name: "Одяг", url: "" },
      { name: "Рушники", url: "" },
      { name: "Інструменти", url: "" },
      { name: "Cyberfishing", url: "" },
      { name: "Туризм", url: "" },
      { name: "Човни й мотори", url: "" },
      { name: "Ехолоти, навігатори і аксесуари", url: "" },
      { name: "Сувенірна продукція", url: "" },
      { name: "Акційні набори", url: "" },
      { name: "Подарункові сертифікати Flagman", url: "" },
      { name: "Запчастини й догляд", url: "" },
      { name: "Тактичне спорядження", url: "" },
      { name: "Автономне живлення", url: "" },
    ],
  },
  {
    name: "Короп",
    catalog: [
      { name: "Вудилища", url: "" },
      { name: "Котушки", url: "" },
      { name: "Шнури", url: "" },
      { name: "Жилки", url: "" },
      { name: "Гачки", url: "" },
      { name: "Силіконові принади", url: "" },
      { name: "Блешні", url: "" },
      { name: "Воблери", url: "" },
      { name: "Гачки", url: "" },
      { name: "Приманки", url: "" },
      { name: "Прикормки", url: "" },
      { name: "Підгодовування", url: "" },
      { name: "Відра", url: "" },
      { name: "Сита", url: "" },
      { name: "Підставки й тримачі", url: "" },
      { name: "Електронні сигналізатори", url: "" },
      { name: "Механічні сигналізатори", url: "" },
      { name: "Підсаки й багри", url: "" },
      { name: "Садки, кукани й кани", url: "" },
      { name: "Догляд за коропом", url: "" },
      { name: "Транспортування й зберігання", url: "" },
      { name: "Парасолі", url: "" },
      { name: "Платформи, крісла та навісне обладнання", url: "" },
      { name: "Зимова ловля", url: "" },
      { name: "Одяг", url: "" },
      { name: "Рушники", url: "" },
      { name: "Інструменти", url: "" },
      { name: "Cyberfishing", url: "" },
      { name: "Туризм", url: "" },
      { name: "Човни й мотори", url: "" },
      { name: "Ехолоти, навігатори і аксесуари", url: "" },
      { name: "Сувенірна продукція", url: "" },
      { name: "Акційні набори", url: "" },
      { name: "Подарункові сертифікати Flagman", url: "" },
      { name: "Запчастини й догляд", url: "" },
      { name: "Тактичне спорядження", url: "" },
      { name: "Автономне живлення", url: "" },
    ],
  },
  {
    name: "Поплавок",
    catalog: [
      { name: "Вудилища", url: "" },
      { name: "Котушки", url: "" },
      { name: "Шнури", url: "" },
      { name: "Жилки", url: "" },
      { name: "Гачки", url: "" },
      { name: "Силіконові принади", url: "" },
      { name: "Блешні", url: "" },
      { name: "Воблери", url: "" },
      { name: "Гачки", url: "" },
      { name: "Приманки", url: "" },
      { name: "Прикормки", url: "" },
      { name: "Підгодовування", url: "" },
      { name: "Відра", url: "" },
      { name: "Сита", url: "" },
      { name: "Підставки й тримачі", url: "" },
      { name: "Електронні сигналізатори", url: "" },
      { name: "Механічні сигналізатори", url: "" },
      { name: "Підсаки й багри", url: "" },
      { name: "Садки, кукани й кани", url: "" },
      { name: "Догляд за коропом", url: "" },
      { name: "Транспортування й зберігання", url: "" },
      { name: "Парасолі", url: "" },
      { name: "Платформи, крісла та навісне обладнання", url: "" },
      { name: "Зимова ловля", url: "" },
      { name: "Одяг", url: "" },
      { name: "Рушники", url: "" },
      { name: "Інструменти", url: "" },
      { name: "Cyberfishing", url: "" },
      { name: "Туризм", url: "" },
      { name: "Човни й мотори", url: "" },
      { name: "Ехолоти, навігатори і аксесуари", url: "" },
      { name: "Сувенірна продукція", url: "" },
      { name: "Акційні набори", url: "" },
      { name: "Подарункові сертифікати Flagman", url: "" },
      { name: "Запчастини й догляд", url: "" },
      { name: "Тактичне спорядження", url: "" },
      { name: "Автономне живлення", url: "" },
    ],
  },
  {
    name: "Зима",
    catalog: [
      { name: "Вудилища", url: "" },
      { name: "Котушки", url: "" },
      { name: "Шнури", url: "" },
      { name: "Жилки", url: "" },
      { name: "Гачки", url: "" },
      { name: "Силіконові принади", url: "" },
      { name: "Блешні", url: "" },
      { name: "Воблери", url: "" },
      { name: "Гачки", url: "" },
      { name: "Приманки", url: "" },
      { name: "Прикормки", url: "" },
      { name: "Підгодовування", url: "" },
      { name: "Відра", url: "" },
      { name: "Сита", url: "" },
      { name: "Підставки й тримачі", url: "" },
      { name: "Електронні сигналізатори", url: "" },
      { name: "Механічні сигналізатори", url: "" },
      { name: "Підсаки й багри", url: "" },
      { name: "Садки, кукани й кани", url: "" },
      { name: "Догляд за коропом", url: "" },
      { name: "Транспортування й зберігання", url: "" },
      { name: "Парасолі", url: "" },
      { name: "Платформи, крісла та навісне обладнання", url: "" },
      { name: "Зимова ловля", url: "" },
      { name: "Одяг", url: "" },
      { name: "Рушники", url: "" },
      { name: "Інструменти", url: "" },
      { name: "Cyberfishing", url: "" },
      { name: "Туризм", url: "" },
      { name: "Човни й мотори", url: "" },
      { name: "Ехолоти, навігатори і аксесуари", url: "" },
      { name: "Сувенірна продукція", url: "" },
      { name: "Акційні набори", url: "" },
      { name: "Подарункові сертифікати Flagman", url: "" },
      { name: "Запчастини й догляд", url: "" },
      { name: "Тактичне спорядження", url: "" },
      { name: "Автономне живлення", url: "" },
    ],
  },
  {
    name: "Море",
    catalog: [
      { name: "Вудилища", url: "" },
      { name: "Котушки", url: "" },
      { name: "Шнури", url: "" },
      { name: "Жилки", url: "" },
      { name: "Гачки", url: "" },
      { name: "Силіконові принади", url: "" },
      { name: "Блешні", url: "" },
      { name: "Воблери", url: "" },
      { name: "Гачки", url: "" },
      { name: "Приманки", url: "" },
      { name: "Прикормки", url: "" },
      { name: "Підгодовування", url: "" },
      { name: "Відра", url: "" },
      { name: "Сита", url: "" },
      { name: "Підставки й тримачі", url: "" },
      { name: "Електронні сигналізатори", url: "" },
      { name: "Механічні сигналізатори", url: "" },
      { name: "Підсаки й багри", url: "" },
      { name: "Садки, кукани й кани", url: "" },
      { name: "Догляд за коропом", url: "" },
      { name: "Транспортування й зберігання", url: "" },
      { name: "Парасолі", url: "" },
      { name: "Платформи, крісла та навісне обладнання", url: "" },
      { name: "Зимова ловля", url: "" },
      { name: "Одяг", url: "" },
      { name: "Рушники", url: "" },
      { name: "Інструменти", url: "" },
      { name: "Cyberfishing", url: "" },
      { name: "Туризм", url: "" },
      { name: "Човни й мотори", url: "" },
      { name: "Ехолоти, навігатори і аксесуари", url: "" },
      { name: "Сувенірна продукція", url: "" },
      { name: "Акційні набори", url: "" },
      { name: "Подарункові сертифікати Flagman", url: "" },
      { name: "Запчастини й догляд", url: "" },
      { name: "Тактичне спорядження", url: "" },
      { name: "Автономне живлення", url: "" },
    ],
  },
  {
    name: "Туризм",
    catalog: [
      { name: "Вудилища", url: "" },
      { name: "Котушки", url: "" },
      { name: "Шнури", url: "" },
      { name: "Жилки", url: "" },
      { name: "Гачки", url: "" },
      { name: "Силіконові принади", url: "" },
      { name: "Блешні", url: "" },
      { name: "Воблери", url: "" },
      { name: "Гачки", url: "" },
      { name: "Приманки", url: "" },
      { name: "Прикормки", url: "" },
      { name: "Підгодовування", url: "" },
      { name: "Відра", url: "" },
      { name: "Сита", url: "" },
      { name: "Підставки й тримачі", url: "" },
      { name: "Електронні сигналізатори", url: "" },
      { name: "Механічні сигналізатори", url: "" },
      { name: "Підсаки й багри", url: "" },
      { name: "Садки, кукани й кани", url: "" },
      { name: "Догляд за коропом", url: "" },
      { name: "Транспортування й зберігання", url: "" },
      { name: "Парасолі", url: "" },
      { name: "Платформи, крісла та навісне обладнання", url: "" },
      { name: "Зимова ловля", url: "" },
      { name: "Одяг", url: "" },
      { name: "Рушники", url: "" },
      { name: "Інструменти", url: "" },
      { name: "Cyberfishing", url: "" },
      { name: "Туризм", url: "" },
      { name: "Човни й мотори", url: "" },
      { name: "Ехолоти, навігатори і аксесуари", url: "" },
      { name: "Сувенірна продукція", url: "" },
      { name: "Акційні набори", url: "" },
      { name: "Подарункові сертифікати Flagman", url: "" },
      { name: "Запчастини й догляд", url: "" },
      { name: "Тактичне спорядження", url: "" },
      { name: "Автономне живлення", url: "" },
    ],
  },
  {
    name: "Екірування",
    catalog: [
      { name: "Вудилища", url: "" },
      { name: "Котушки", url: "" },
      { name: "Шнури", url: "" },
      { name: "Жилки", url: "" },
      { name: "Гачки", url: "" },
      { name: "Силіконові принади", url: "" },
      { name: "Блешні", url: "" },
      { name: "Воблери", url: "" },
      { name: "Гачки", url: "" },
      { name: "Приманки", url: "" },
      { name: "Прикормки", url: "" },
      { name: "Підгодовування", url: "" },
      { name: "Відра", url: "" },
      { name: "Сита", url: "" },
      { name: "Підставки й тримачі", url: "" },
      { name: "Електронні сигналізатори", url: "" },
      { name: "Механічні сигналізатори", url: "" },
      { name: "Підсаки й багри", url: "" },
      { name: "Садки, кукани й кани", url: "" },
      { name: "Догляд за коропом", url: "" },
      { name: "Транспортування й зберігання", url: "" },
      { name: "Парасолі", url: "" },
      { name: "Платформи, крісла та навісне обладнання", url: "" },
      { name: "Зимова ловля", url: "" },
      { name: "Одяг", url: "" },
      { name: "Рушники", url: "" },
      { name: "Інструменти", url: "" },
      { name: "Cyberfishing", url: "" },
      { name: "Туризм", url: "" },
      { name: "Човни й мотори", url: "" },
      { name: "Ехолоти, навігатори і аксесуари", url: "" },
      { name: "Сувенірна продукція", url: "" },
      { name: "Акційні набори", url: "" },
      { name: "Подарункові сертифікати Flagman", url: "" },
      { name: "Запчастини й догляд", url: "" },
      { name: "Тактичне спорядження", url: "" },
      { name: "Автономне живлення", url: "" },
    ],
  },
]
